---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ic-app
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ic-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ic-app
        deployment: ic-app
        azure.workload.identity/use: true
    spec:
      serviceAccountName: parasol
      volumes:
        - name: dot-env
          secret:
            secretName: dot-env
      containers:
        - name: insurance-claim-app
          volumeMounts:
            - mountPath: /opt/app-root/src/.env
              subPath: .env
              name: dot-env
              readOnly: true
          image: ghcr.io/rh-mobb/rhoai-lab-insurance-claim-app:miwi
          # ghcr.io/scorpiion/parasol-insurance/parasol-app:latest
          ports:
            - containerPort: 5000
              protocol: TCP
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: INFERENCE_SERVER_URL
              value: http://llm.ic-shared-llm.svc.cluster.local:8000/v1
            - name: MODEL_NAME
              value: 'mistralai/Mistral-7B-Instruct-v0.2'
            - name: MAX_TOKENS
              value: '512'
            - name: TOP_P
              value: '0.95'
            - name: TEMPERATURE
              value: '0.01'
            - name: PRESENCE_PENALTY
              value: '1.03'
            - name: AI_SERVICE
              value: azure
            - name: STORAGE_SERVICE
              value: aws
            - name: POSTGRES_HOST
              value: claimdb.$(NAMESPACE).svc.cluster.local
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: claimdb
                  key: database-name
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: claimdb
                  key: database-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: claimdb
                  key: database-password
            - name: POSTGRES_PORT
              value: '5432'
            - name: S3_ENDPOINT_URL
              value: http://minio.ic-shared-minio.svc.cluster.local:9000
            - name: IMAGES_BUCKET
              value: $(NAMESPACE)
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: secret-minio
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-minio
                  key: aws_secret_access_key
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600