FROM quay.io/modh/odh-generic-data-science-notebook@sha256:7bf5f368d452d461b7c6517c1142ca36475f3ce8a84ab04b498002c2fbf06dde

RUN pip install --upgrade pip

RUN pip install pipenv \
    langchain_aws \
    text_generation \
    opencv-python ultralytics \
    'numpy<2' \
    torch==2.2.2+cpu --extra-index-url https://download.pytorch.org/whl/cpu
